keys:
  key1,
  key2,
  key3,



questionThree:
  max_tokens: 2800
  top_p: 1
  temperature: 0.5
  frequency_penalty: 0
  presence_penalty: 0

server:
  port: 9998

spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/gptdatabase?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      maxActive: 200

mybatis-plus:
  #  configuration:
  #    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑未删除值，（逻辑删除下有效）
      logic-delete-value: 1
      #逻辑未删除值，（逻辑删除下有效）需要注入逻辑策略LogicSqlInjector，以@Bean方式注      入
      logic-not-delete-value: 0

oss:
  accessId: accessId
  accessKey: accessKey
  endpoint: endpoint
  bucketName: bucketName




